services:
  db:
    image: mariadb-image
    container_name: mariadb-container
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: on-failure
    expose: 
      - '3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - data:/var/lib/mysql
    networks:
      - inception_network
  wordpress:
   image: wordpress-image
   container_name: wordpress-container
   build:
     context: ./requirements/wordpress
     dockerfile: Dockerfile
   restart: on-failure
   expose:
     - '9000'
   environment:
     WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
     WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
     WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
     WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
   depends_on:
     - db
   volumes:
     - wp_files:/var/www/html
   networks:
     - inception_network
#  nginx:
#    image: nginx-image
#    container-name: nginx-container
#    build:
#      context: ./requirements/nginx
#      dockerfile: Dockerfile
#    restart: on-failure
#    ports:
#      - "443:443"
#    depends-on:
#      - wordpress
#    volumes:
#      - wp_files
#    networks:
#      - inception_network

volumes:
  data:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: "/home/${USER}/data/mariadb-volume"
  wp_files:
    driver: local
    driver_opts:
     type: 'none'
     o: bind
     device: "/home/${USER}/data/wordpress-nginx-volume"   

networks:
  inception_network:
    driver: bridge
